### ISSUE TITLE
503 Service Temporarily Unavailable nginx/1.17.10

### ISSUE THREAD

**Issue by boschpeter** [boschpeter/Workbook_Docker_fundamentals#9]
````503 Service Temporarily Unavailable nginx/1.17.10````

## deployment_clerk_frontend.yaml
````
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: clerk-frontend-app # Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clerk-frontend-app
  template:
    metadata:
      labels:
        app: clerk-frontend-app
        ingress-frontoffice-policy: allow
    spec:
      containers:
        - name: clerk-frontend-app
          image: harbor-ot.l12m.nl/waardepapieren-demo/clerk-frontend:lpc 
          imagePullPolicy: Always
          resources:
            requests:
              memory: 50Mi # 50 Megabytes
              cpu: 100m # 1 CPU = 1000 > 300m is 300/1000 = 10% CPU
            limits:
              memory: 50Mi
              cpu: 100m
      imagePullSecrets: # https://kubernetes.io/docs/concepts/configuration/secret/#using-imagepullsecrets
      - name: harbor-puller        

# kubectl-oidc_login   
# kubectl apply -f deployment_clerk_frontend.yaml -n hack-ontwikkel --insecure-skip-tls-verify=true  
````

##   service_clerk_frontend.yaml

````
--- 
apiVersion: v1
kind: Service
metadata:
  name: clerk-frontend-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: clerk-frontend-service

# kubectl-oidc_login   
# kubectl apply -f service_clerk_frontend.yaml -n hack-ontwikkel --insecure-skip-tls-verify=true    

````
## kubectl apply -f ingress_clerk_frontend.yaml -n hack-ontwikkel --insecure-skip-tls-verify=true    
````
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.class: nginx
  name: clerk-frontend-ingress
spec:
  rules:
  - host: waardepapieren-demo.hack-ontwikkel.lpc-ot2.l12m.nl
    http:
      paths:
      - backend:
          serviceName: clerk-frontend-service
          servicePort: 8080
        path: /
  tls:
  - secretName: wildcard-tls
    hosts:
    - waardepapieren-demo.hack-ontwikkel.lpc-ot2.l12m.nl

````
